export const LAYOUT = {
  CONTENT_MARGIN: 10,
  PARAM_MARGIN: 6,
  MARKDOWN_MARGIN: 12,
} as const;

export const TRUNCATION = {
  DEFAULT_MAX_LINES: 5,
  BASH_MAX_LINES: 10,
  DEFAULT_MAX_LINE_LENGTH: 150,
  BASH_MAX_LINE_LENGTH: 200,
} as const;
