// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct - simplified to use services
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from '@wailsio/runtime';

/**
 * CheckForUpdates fetches latest release info and prompts the user to update.
 */
export function CheckForUpdates(): $CancellablePromise<void> {
  return $Call.ByID(2675659504);
}
