// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Debug is a simple Wails v3 service for ad-hoc logging/tests.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * LogRandomTest logs a simple debug message with a random value and returns it.
 */
export function LogRandomTest(): $CancellablePromise<string> {
    return $Call.ByID(154956394);
}
