// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService provides simple in-app update checks.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CheckForUpdates fetches latest release info and prompts the user to update.
 */
export function CheckForUpdates(): $CancellablePromise<void> {
    return $Call.ByID(670986527);
}

/**
 * OnStartup captures Wails context for dialogs/logging.
 */
export function OnStartup(): $CancellablePromise<void> {
    return $Call.ByID(600007742);
}
