// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface FileFilter {
  DisplayName: string;
  Pattern: string;
}

export interface OpenDialogOptions {
  Title: string;
  DefaultFilename: string;
  DefaultDirectory: string;
  Filters: FileFilter[] | null;
  ShowHiddenFiles: boolean;
  CanCreateDirectories: boolean;
  ResolvesAliases: boolean;
}

export interface SaveDialogOptions {
  Title: string;
  DefaultFilename: string;
  DefaultDirectory: string;
  Filters: FileFilter[] | null;
  ShowHiddenFiles: boolean;
  CanCreateDirectories: boolean;
}
