// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { main } from '../models';

export function CheckForUpdates(): Promise<void>;

export function FetchGithubCopilotKey(): Promise<string>;

export function FetchProxy(
  arg1: main.FetchRequest,
): Promise<main.FetchResponse>;

export function GetMCPServerStatus(): Promise<Record<string, string>>;

export function Greet(arg1: string): Promise<string>;

export function SendMCPMessage(
  arg1: string,
  arg2: main.MCPMessage,
): Promise<void>;

export function StartMCPServer(arg1: main.MCPRequest): Promise<void>;

export function StopAllMCPServers(): Promise<void>;

export function StopMCPServer(arg1: string): Promise<void>;
