// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function FetchGithubCopilotKey() {
  return window['go']['main']['App']['FetchGithubCopilotKey']();
}

export function FetchProxy(arg1) {
  return window['go']['main']['App']['FetchProxy'](arg1);
}

export function GetMCPServerStatus() {
  return window['go']['main']['App']['GetMCPServerStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function MkdirAll(arg1) {
  return window['go']['main']['App']['MkdirAll'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function Remove(arg1, arg2) {
  return window['go']['main']['App']['Remove'](arg1, arg2);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function SendMCPMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMCPMessage'](arg1, arg2);
}

export function StartMCPServer(arg1) {
  return window['go']['main']['App']['StartMCPServer'](arg1);
}

export function StopAllMCPServers() {
  return window['go']['main']['App']['StopAllMCPServers']();
}

export function StopMCPServer(arg1) {
  return window['go']['main']['App']['StopMCPServer'](arg1);
}

export function WriteFile(arg1) {
  return window['go']['main']['App']['WriteFile'](arg1);
}
