// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchGithubCopilotKey():Promise<string>;

export function FetchProxy(arg1:main.FetchRequest):Promise<main.FetchResponse>;

export function Greet(arg1:string):Promise<string>;
