version: '3'

# Wails v3 uses `wails3 task <name>` to invoke these tasks.
vars:
  DEV_URL: http://localhost:5173
  APP_NAME: nuvin-space
  APP_DISPLAY: Nuvin Space
  VERSION:
    sh: |
      grep -o '"productVersion": "[^"]*"' wails.json | sed -E 's/.*"([^"]+)"/\1/'
  GOOS:
    sh: go env GOOS
  GOARCH:
    sh: go env GOARCH

tasks:
  frontend:install:
    dir: frontend
    cmds:
      - pnpm install

  frontend:build:
    dir: frontend
    cmds:
      - wails3 generate bindings -ts -i
      - pnpm build

  frontend:dev:
    dir: frontend
    cmds:
      - pnpm dev

  dev:
    desc: Run Vite + app in dev mode
    deps: [frontend:install]
    env:
      FRONTEND_DEVSERVER_URL: "{{.DEV_URL}}"
    cmds:
      - wails3 generate bindings -ts -i
      - |
        (cd frontend && pnpm dev) &
      - go run .

  build:
    desc: Build frontend then desktop binary
    deps: [frontend:build]
    cmds:
      - mkdir -p build
      - go build -o build/{{.APP_NAME}} .

  package:prepare:
    desc: Prepare dist directory and copy built binary with versioned name
    deps: [build]
    cmds:
      - mkdir -p dist
      - cp build/{{.APP_NAME}} dist/{{.APP_NAME}}_{{.VERSION}}_{{.GOOS}}-{{.GOARCH}}{{if eq .GOOS "windows"}}.exe{{end}}

  package:archive:
    desc: Create a simple archive for the current platform (zip on macOS/Windows, tar.gz on Linux)
    deps: [package:prepare]
    cmds:
      - |
        if [ "{{.GOOS}}" = "linux" ]; then \
          tar czf dist/{{.APP_NAME}}_{{.VERSION}}_{{.GOOS}}-{{.GOARCH}}.tar.gz -C dist {{.APP_NAME}}_{{.VERSION}}_{{.GOOS}}-{{.GOARCH}} ; \
        else \
          cd dist && zip -r {{.APP_NAME}}_{{.VERSION}}_{{.GOOS}}-{{.GOARCH}}.zip {{.APP_NAME}}_{{.VERSION}}_{{.GOOS}}-{{.GOARCH}}{{if eq .GOOS "windows"}}.exe{{end}} ; \
        fi

  package:mac:dmg:
    desc: Create a minimal DMG containing the app binary (macOS only)
    deps: [package:prepare]
    cmds:
      - |
        if [ "{{.GOOS}}" != "darwin" ]; then echo "This task must be run on macOS" && exit 1; fi
      - rm -rf dist/dmg && mkdir -p dist/dmg
      - cp dist/{{.APP_NAME}}_{{.VERSION}}_{{.GOOS}}-{{.GOARCH}} dist/dmg/{{.APP_NAME}}
      - hdiutil create dist/{{.APP_NAME}}_{{.VERSION}}_macOS.dmg -volname "{{.APP_NAME}}" -srcfolder dist/dmg -ov -fs HFS+

  package:mac:app:
    desc: Build a proper macOS .app bundle (no Terminal)
    deps: [build]
    cmds:
      - |
        if [ "{{.GOOS}}" != "darwin" ]; then echo "This task must be run on macOS" && exit 1; fi
      - APP_DIR="dist/{{.APP_DISPLAY}}.app"; rm -rf "$APP_DIR" && mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"
      - cp build/{{.APP_NAME}} "dist/{{.APP_DISPLAY}}.app/Contents/MacOS/{{.APP_NAME}}"
      - chmod +x "dist/{{.APP_DISPLAY}}.app/Contents/MacOS/{{.APP_NAME}}"
      - |
        cat > "dist/{{.APP_DISPLAY}}.app/Contents/Info.plist" << 'PLIST'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CFBundleName</key><string>{{.APP_DISPLAY}}</string>
          <key>CFBundleDisplayName</key><string>{{.APP_DISPLAY}}</string>
          <key>CFBundleIdentifier</key><string>com.marschhuynh.nuvin-space</string>
          <key>CFBundleExecutable</key><string>{{.APP_NAME}}</string>
          <key>CFBundleShortVersionString</key><string>{{.VERSION}}</string>
          <key>CFBundleVersion</key><string>{{.VERSION}}</string>
          <key>CFBundlePackageType</key><string>APPL</string>
          <key>LSMinimumSystemVersion</key><string>10.13</string>
          <key>LSApplicationCategoryType</key><string>public.app-category.productivity</string>
          <key>NSHighResolutionCapable</key><true/>
          <key>NSPrincipalClass</key><string>NSApplication</string>
          <key>CFBundleIconFile</key><string>appicon.icns</string>
        </dict>
        </plist>
        PLIST
      - |
        # Generate .icns from icons/appstore.png if possible
        ICON_SRC="icons/appstore.png"; APP_RES="dist/{{.APP_DISPLAY}}.app/Contents/Resources"
        if command -v iconutil >/dev/null 2>&1 && command -v sips >/dev/null 2>&1 && [ -f "$ICON_SRC" ]; then \
          TMPSET=$(mktemp -d)/AppIcon.iconset; mkdir -p "$TMPSET"; \
          for SIZE in 16 32 64 128 256 512; do \
            sips -z $SIZE $SIZE "$ICON_SRC" --out "$TMPSET/icon_${SIZE}x${SIZE}.png" >/dev/null; \
            sips -z $((SIZE*2)) $((SIZE*2)) "$ICON_SRC" --out "$TMPSET/icon_${SIZE}x${SIZE}@2x.png" >/dev/null; \
          done; \
          iconutil -c icns "$TMPSET" -o "$APP_RES/appicon.icns"; \
        else \
          echo "Skipping .icns generation (iconutil/sips not available or icon missing)"; \
        fi
      - |
        # Ad-hoc sign to avoid Gatekeeper warnings in some cases (replace with your cert for distribution)
        codesign --force --deep -s - --timestamp=none "dist/{{.APP_DISPLAY}}.app" || true

  package:mac:dmg-app:
    desc: Create a DMG with the .app bundle and Applications link (macOS only)
    deps: [package:mac:app]
    cmds:
      - |
        if [ "{{.GOOS}}" != "darwin" ]; then echo "This task must be run on macOS" && exit 1; fi
      - rm -rf dist/dmg-app && mkdir -p dist/dmg-app
      - cp -R "dist/{{.APP_DISPLAY}}.app" dist/dmg-app/
      - ln -s /Applications dist/dmg-app/Applications || true
      - hdiutil create "dist/{{.APP_DISPLAY}}_{{.VERSION}}.dmg" -volname "{{.APP_DISPLAY}}" -srcfolder dist/dmg-app -ov -fs HFS+

  package:win:zip:
    desc: Zip the Windows executable (run on Windows build machine)
    deps: [package:prepare]
    cmds:
      - |
        if [ "{{.GOOS}}" != "windows" ]; then echo "This task should be run on Windows"; fi
      - cd dist && zip -r {{.APP_NAME}}_{{.VERSION}}_windows-{{.GOARCH}}.zip {{.APP_NAME}}_{{.VERSION}}_windows-{{.GOARCH}}.exe

  package:linux:tar:
    desc: Tar/Gzip the Linux binary (run on Linux build machine)
    deps: [package:prepare]
    cmds:
      - |
        if [ "{{.GOOS}}" != "linux" ]; then echo "This task should be run on Linux"; fi
      - tar czf dist/{{.APP_NAME}}_{{.VERSION}}_linux-{{.GOARCH}}.tar.gz -C dist {{.APP_NAME}}_{{.VERSION}}_linux-{{.GOARCH}}

  generate:icon:
    desc: Generate .icns icon from icons/appstore.png (macOS only)
    cmds:
      - |
        if [ "{{.GOOS}}" != "darwin" ]; then echo "This task must be run on macOS" && exit 1; fi
      - mkdir -p icons
      - |
        ICON_SRC="icons/appstore.png"
        if [ ! -f "$ICON_SRC" ]; then echo "Source icon not found: $ICON_SRC" && exit 1; fi
      - |
        # Generate .icns from icons/appstore.png
        ICON_SRC="icons/appstore.png"
        if command -v iconutil >/dev/null 2>&1 && command -v sips >/dev/null 2>&1 && [ -f "$ICON_SRC" ]; then \
          TMPSET=$(mktemp -d)/AppIcon.iconset; mkdir -p "$TMPSET"; \
          echo "Generating icon sizes..."; \
          for SIZE in 16 32 64 128 256 512; do \
            echo "  Creating ${SIZE}x${SIZE} icon..."; \
            sips -z $SIZE $SIZE "$ICON_SRC" --out "$TMPSET/icon_${SIZE}x${SIZE}.png" >/dev/null; \
            sips -z $((SIZE*2)) $((SIZE*2)) "$ICON_SRC" --out "$TMPSET/icon_${SIZE}x${SIZE}@2x.png" >/dev/null; \
          done; \
          echo "Generating .icns file..."; \
          iconutil -c icns "$TMPSET" -o "icons/appicon.icns"; \
          echo "Icon generated successfully: icons/appicon.icns"; \
        else \
          echo "Error: iconutil/sips not available or source icon missing"; \
          exit 1; \
        fi
