// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitHubOAuthService handles GitHub authentication and returns access token
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from '@wailsio/runtime';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from './models.js';

/**
 * FetchGithubCopilotKey handles GitHub authentication and returns access token and API key
 */
export function FetchGithubCopilotKey(): $CancellablePromise<$models.GitHubTokenResponse> {
  return $Call.ByID(1930712992);
}

/**
 * OnStartup initializes the GitHub OAuth service
 */
export function OnStartup(): $CancellablePromise<void> {
  return $Call.ByID(3589567810);
}
