// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HTTPProxyService handles HTTP requests from JavaScript, bypassing CORS and browser restrictions
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FetchProxy handles HTTP requests from JavaScript, bypassing CORS and browser restrictions
 */
export function FetchProxy(fetchReq: $models.FetchRequest): $CancellablePromise<$models.FetchResponse> {
    return $Call.ByID(1094590646, fetchReq);
}

/**
 * OnStartup initializes the HTTP proxy service
 */
export function OnStartup(): $CancellablePromise<void> {
    return $Call.ByID(2038031856);
}
