// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StreamingService handles streaming response data via Wails events
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from '@wailsio/runtime';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as io$0 from '../../io/models.js';

/**
 * OnStartup initializes the streaming service
 */
export function OnStartup(): $CancellablePromise<void> {
  return $Call.ByID(1025963888);
}

/**
 * StreamResponse handles streaming response data via Wails events
 */
export function StreamResponse(streamID: string, body: io$0.ReadCloser): $CancellablePromise<void> {
  return $Call.ByID(2651789913, streamID, body);
}
