// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ReadCloser is the interface that groups the basic Read and Close methods.
 */
export type ReadCloser = any;
